### ISSUE TITLE
请问一下编写插件的时候怎么进行调试？

### ISSUE THREAD

**Issue by knight0zh** [lvht/protoc-gen-markdown#8]
如果每次调试都需要编译一下会特别麻烦，也无法使用debug等工具

**Comment by taoso** [comment]
你这个问题非常好。

因为插件是通过 protoc 调用的，并不有特别好的方式来实现单步调试。

我一直使用 print 大法。不过你不能直接打印调试信息，这会影响 protoc 跟插件之前的通信。
正确的做法是打印到 stderr

```go
fmt.Fprintf(os.Stderr, "Fprintln: %v\n", err)
```
